### ISSUE TITLE
3b Sprint planning. Remove semi-colons and add space.

### ISSUE THREAD

**Issue by amydarling** [publiccodenet/processcode.publiccode.net#14]
1. Under Sprint planning , see: https://processcode.publiccode.net/4b-agile-development.html

we use ; in the list

Other sections with similar short lists (see 3b) use no punctuation. I would suggest removing the ; for consistency.

2. Also, we need an extra line after:
"Integrated, tested and operationalized at the end of the sprint." 

as it crowds into the next big icon item

Work with the development team to plan the first sprint.

(see guidelines below)

**Comment by angelplasma** [comment]
Agree. Fixed.
