### ISSUE TITLE
4c. #11 is labelled as Github, but it isn't. Label should be changed.

### ISSUE THREAD

**Issue by amydarling** [publiccodenet/processcode.publiccode.net#16]
The tag should be "Open Source Guides" instead of Github for #11: "The Legal Side of Open Source".

Also, capitalization of all these links are inconsistent. Even the articles are initial capped in the list, but when you follow the links, it is consistent with previous sections with sentence capitalization - like for #9 https://ben.balter.com/2014/10/08/open-source-licensing-for-government-attorneys/.

**Comment by angelplasma** [comment]
You're right - I don't know if some articles got changed at some point, but the capitalization, titles, and a few links were either out of date or wrong on a number of these. I've done a full pass on every link, and I think I've reconciled them all* in both the web and PDF versions.

* ...aside from a couple covered in other open tickets
