### ISSUE TITLE
Navigation not working consistently

### ISSUE THREAD

**Issue by mcarlson** [publiccodenet/processcode.publiccode.net#23]

**Comment by mcarlson** [comment]
The navbar on the right isn't working consistently:
+ 'a. Welcome!' isn't linked from the navbar, e.g. https://processcode.publiccode.net/1bu46-capacity-building.html should link to https://processcode.publiccode.net/1au46-getting-oriented.html
+ 'b. Capacity building' link broken from https://processcode.publiccode.net/1au46-getting-oriented.html
+

**Comment by angelplasma** [comment]
The nav is now relinked and resented to 'Anima export 7'.
