### ISSUE TITLE
Line height is incorrect in 4a

### ISSUE THREAD

**Issue by mcarlson** [publiccodenet/processcode.publiccode.net#27]
Please break into separate text boxes in Figma. Per their support team: 

By the way another workaround could be to create each paragraph as a separate text section with the desired gaps between sections and autolayout as well to maintain the correct layout.

**Comment by angelplasma** [comment]
I've re-exported this, and it now has the right line-height, but paragraph separations are still missing.

This text box is set up the same way as on 3a, 2a, etc. Same text style, same box formatting... Unclear why this one is having issues.

Breaking all paragraphs into their own blocks might help this issue, though adds further friction around updating content. Is that how you'd like to proceed?

**Comment by angelplasma** [comment]
Paragraphs broken up for now, for the quick fix.
