### ISSUE TITLE
Figma: Missing link for item 5 'Tech Reset Canada  Procurement Reform and Requirement Writing' in https://processcode.publiccode.net/2c-rfp-writing.html.

### ISSUE THREAD

**Issue by mcarlson** [publiccodenet/processcode.publiccode.net#5]
@matthewclaudel Can you paste the link here? Thanks!  If not, we can remove it for this version. Please advise.

**Comment by amydarling** [comment]
Per @matthewclaudel Please use: https://www.techresetcanada.org/procurement

**Comment by angelplasma** [comment]
Link updated
