### ISSUE TITLE
3b Vendor interactions - recommend free (not Industry Navigator)

### ISSUE THREAD

**Issue by amydarling** [publiccodenet/processcode.publiccode.net#8]
I use https://sam.gov/content/opportunities (without logging in) to look directly at gov contracts - mainly because it is free. I also use bidnet (the free version).  The more generic link would be https://sam.gov/search/

@matthewclaudel Is there another that you use?

**Comment by amydarling** [comment]
Go with the generic link!

**Comment by angelplasma** [comment]
Updated.
