### ISSUE TITLE
3c. Link should be Initial cap then all lower case for consistency

### ISSUE THREAD

**Issue by amydarling** [publiccodenet/processcode.publiccode.net#9]
The link text in section 3c for item 4 is using Initial Cap for all words in title: 
[An Open Source Software Tool for Comparing Bids](https://github.com/ForumViriumHelsinki/ApplicationEvaluator)

This is inconsistent. Even the first link is an article and we've lower-cased all subsequent words.

This link should be "An open source software tool for comparing bids" to be consistent.

**Comment by angelplasma** [comment]
Fixed this - def agree a descriptive phrase (not even a title) like this one should be sentence case. Else, precedent is generally to copy capitalization from source.
